name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # https://github.com/adamralph/minver#why-is-the-default-version-sometimes-used-in-github-actions-and-travis-ci-when-a-version-tag-exists-in-the-history
    
    - name: Setup .NET Core SDK - latest
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0.100-rc.2.20479.15'

    - name: Setup .NET Core SDK - 2.1
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '2.1.x'
        
    - name: set script permissions
      run: chmod +x ./build.sh

    - name: build
      run: ./build.sh test