name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: [main, develop]
    types: 
      - completed

env:
  FeedzApiKey: ${{ secrets.FEEDZ_API_KEY }}
  NuGetApiKey: ${{ secrets.NUGET_API_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # https://github.com/adamralph/minver#why-is-the-default-version-sometimes-used-in-github-actions-and-travis-ci-when-a-version-tag-exists-in-the-history

    - name: Setup .NET SDK - latest
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.*'

    - name: set script permissions
      run: chmod +x ./build.sh

    - name: package and publish
      run: ./build.sh publish
  